// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrtYf6alxo-J3nmdhXkdQ7SHgNnTYVyPg',
    appId: '1:641320445560:android:31ff99d588706b00656f8d',
    messagingSenderId: '641320445560',
    projectId: 'flutterpractice-81d03',
    databaseURL: 'https://flutterpractice-81d03-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterpractice-81d03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP3TKk5H3YHsItiXKiXeVOF1FV6SGA3mU',
    appId: '1:641320445560:ios:c1111de484aa16b9656f8d',
    messagingSenderId: '641320445560',
    projectId: 'flutterpractice-81d03',
    databaseURL: 'https://flutterpractice-81d03-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterpractice-81d03.appspot.com',
    iosClientId: '641320445560-gforqi15a0jlrae8phs66op8hq0v2urg.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutorial',
  );
}
